package com.app.project.blooddonorfinder.DataModels;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.app.project.blooddonorfinder.DataModels.Hospital;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOSPITAL".
*/
public class HospitalDao extends AbstractDao<Hospital, Long> {

    public static final String TABLENAME = "HOSPITAL";

    /**
     * Properties of entity Hospital.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, Long.class, "userId", false, "USER_ID");
        public final static Property HospitalName = new Property(2, String.class, "hospitalName", false, "HOSPITAL_NAME");
        public final static Property HospitalAddress = new Property(3, String.class, "hospitalAddress", false, "HOSPITAL_ADDRESS");
        public final static Property Email = new Property(4, String.class, "email", false, "EMAIL");
        public final static Property Speciality = new Property(5, String.class, "speciality", false, "SPECIALITY");
        public final static Property PhoneNumber = new Property(6, String.class, "phoneNumber", false, "PHONE_NUMBER");
        public final static Property HospitalLicense = new Property(7, String.class, "hospitalLicense", false, "HOSPITAL_LICENSE");
        public final static Property AlternativePhonenumber = new Property(8, String.class, "alternativePhonenumber", false, "ALTERNATIVE_PHONENUMBER");
    };


    public HospitalDao(DaoConfig config) {
        super(config);
    }
    
    public HospitalDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOSPITAL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_ID\" INTEGER," + // 1: userId
                "\"HOSPITAL_NAME\" TEXT," + // 2: hospitalName
                "\"HOSPITAL_ADDRESS\" TEXT," + // 3: hospitalAddress
                "\"EMAIL\" TEXT," + // 4: email
                "\"SPECIALITY\" TEXT," + // 5: speciality
                "\"PHONE_NUMBER\" TEXT," + // 6: phoneNumber
                "\"HOSPITAL_LICENSE\" TEXT," + // 7: hospitalLicense
                "\"ALTERNATIVE_PHONENUMBER\" TEXT);"); // 8: alternativePhonenumber
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOSPITAL\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Hospital entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(2, userId);
        }
 
        String hospitalName = entity.getHospitalName();
        if (hospitalName != null) {
            stmt.bindString(3, hospitalName);
        }
 
        String hospitalAddress = entity.getHospitalAddress();
        if (hospitalAddress != null) {
            stmt.bindString(4, hospitalAddress);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(5, email);
        }
 
        String speciality = entity.getSpeciality();
        if (speciality != null) {
            stmt.bindString(6, speciality);
        }
 
        String phoneNumber = entity.getPhoneNumber();
        if (phoneNumber != null) {
            stmt.bindString(7, phoneNumber);
        }
 
        String hospitalLicense = entity.getHospitalLicense();
        if (hospitalLicense != null) {
            stmt.bindString(8, hospitalLicense);
        }
 
        String alternativePhonenumber = entity.getAlternativePhonenumber();
        if (alternativePhonenumber != null) {
            stmt.bindString(9, alternativePhonenumber);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Hospital readEntity(Cursor cursor, int offset) {
        Hospital entity = new Hospital( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // hospitalName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // hospitalAddress
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // email
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // speciality
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // phoneNumber
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // hospitalLicense
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // alternativePhonenumber
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Hospital entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setHospitalName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHospitalAddress(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setEmail(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSpeciality(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPhoneNumber(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setHospitalLicense(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setAlternativePhonenumber(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Hospital entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Hospital entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
