package com.app.project.blooddonorfinder.DataModels;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HOSPITAL".
 */
public class Hospital {

    private Long id;
    private Long userId;
    private String hospitalName;
    private String hospitalAddress;
    private String email;
    private String speciality;
    private String phoneNumber;
    private String hospitalLicense;
    private String alternativePhonenumber;

    public Hospital() {
    }

    public Hospital(Long id) {
        this.id = id;
    }

    public Hospital(Long id, Long userId, String hospitalName, String hospitalAddress, String email, String speciality, String phoneNumber, String hospitalLicense, String alternativePhonenumber) {
        this.id = id;
        this.userId = userId;
        this.hospitalName = hospitalName;
        this.hospitalAddress = hospitalAddress;
        this.email = email;
        this.speciality = speciality;
        this.phoneNumber = phoneNumber;
        this.hospitalLicense = hospitalLicense;
        this.alternativePhonenumber = alternativePhonenumber;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getHospitalName() {
        return hospitalName;
    }

    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }

    public String getHospitalAddress() {
        return hospitalAddress;
    }

    public void setHospitalAddress(String hospitalAddress) {
        this.hospitalAddress = hospitalAddress;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSpeciality() {
        return speciality;
    }

    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getHospitalLicense() {
        return hospitalLicense;
    }

    public void setHospitalLicense(String hospitalLicense) {
        this.hospitalLicense = hospitalLicense;
    }

    public String getAlternativePhonenumber() {
        return alternativePhonenumber;
    }

    public void setAlternativePhonenumber(String alternativePhonenumber) {
        this.alternativePhonenumber = alternativePhonenumber;
    }

}
