package com.app.project.blooddonorfinder.DataModels;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DONOR".
 */
public class Donor {

    private Long id;
    private Integer userId;
    private String userName;
    private String bloodGroup;
    private String gender;
    private String email;
    private Integer numberOfDonation;
    private Integer readyToDonate;
    private String phoneNumber;
    private String altPhoneNumber;
    private String address;
    private String lastKnownLocation;
    private String lastKnownTime;

    public Donor() {
    }

    public Donor(Long id) {
        this.id = id;
    }

    public Donor(Long id, Integer userId, String userName, String bloodGroup, String gender, String email, Integer numberOfDonation, Integer readyToDonate, String phoneNumber, String altPhoneNumber, String address, String lastKnownLocation, String lastKnownTime) {
        this.id = id;
        this.userId = userId;
        this.userName = userName;
        this.bloodGroup = bloodGroup;
        this.gender = gender;
        this.email = email;
        this.numberOfDonation = numberOfDonation;
        this.readyToDonate = readyToDonate;
        this.phoneNumber = phoneNumber;
        this.altPhoneNumber = altPhoneNumber;
        this.address = address;
        this.lastKnownLocation = lastKnownLocation;
        this.lastKnownTime = lastKnownTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getBloodGroup() {
        return bloodGroup;
    }

    public void setBloodGroup(String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getNumberOfDonation() {
        return numberOfDonation;
    }

    public void setNumberOfDonation(Integer numberOfDonation) {
        this.numberOfDonation = numberOfDonation;
    }

    public Integer getReadyToDonate() {
        return readyToDonate;
    }

    public void setReadyToDonate(Integer readyToDonate) {
        this.readyToDonate = readyToDonate;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getAltPhoneNumber() {
        return altPhoneNumber;
    }

    public void setAltPhoneNumber(String altPhoneNumber) {
        this.altPhoneNumber = altPhoneNumber;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getLastKnownLocation() {
        return lastKnownLocation;
    }

    public void setLastKnownLocation(String lastKnownLocation) {
        this.lastKnownLocation = lastKnownLocation;
    }

    public String getLastKnownTime() {
        return lastKnownTime;
    }

    public void setLastKnownTime(String lastKnownTime) {
        this.lastKnownTime = lastKnownTime;
    }

}
